spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8& #useSSL=false&allowPublicKeyRetrieval=true
    username: planit
    password: planit
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: planit-local-secret-key


jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  show-sql: tru

